# Generated by Django 5.0.7 on 2024-08-05 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=30)),
                ('move_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('COLUMN', 'Column'), ('FOUNDATION', 'Foundation'), ('FREE_CELL', 'Free Cell')], max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecell.game')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('suit', models.CharField(choices=[('HEARTS', 'Hearts'), ('DIAMONDS', 'Diamonds'), ('SPADES', 'Spades'), ('CLUBS', 'Clubs')], max_length=10)),
                ('rank', models.CharField(choices=[('ACE', 'Ace'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six'), ('SEVEN', 'Seven'), ('EIGHT', 'Eight'), ('NINE', 'Nine'), ('TEN', 'Ten'), ('JACK', 'Jack'), ('QUEEN', 'Queen'), ('KING', 'King')], max_length=10)),
                ('sort_order', models.IntegerField()),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freecell.pile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
