# Generated by Django 5.0.7 on 2024-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freecell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
