# Generated by Django 5.0.7 on 2024-08-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freecell', '0002_pile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pile',
            old_name='name',
            new_name='key',
        ),
    ]
